project_id = "xwsgyxlvxntgpochonwe"

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.refund-payment]
verify_jwt = false

[functions.draft-postcard-message]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.ignitepost-webhook]
verify_jwt = false

[functions.send-delivery-notification]
verify_jwt = false

[functions.smart-share]
verify_jwt = false